### PR TITLE
Random anchor

### PR DESCRIPTION
**Pull request by graycarl**
Add configable option to generate a random id as an anchor, for users who is using no-ascii head text.

### CODE REVIEW

**Comment by goanpeca** [comment]
@nixjdm ?

**Comment by goanpeca** [comment]
But we need to update docs or README

**Comment by nixjdm** [comment]
Ah, man. Right you are. I'll make another ticket and get started on that.

**Comment by nixjdm** [comment]
Considering this was so old, that's probably the fastest way of doing that. Though I should have done it first.

**Comment by goanpeca** [comment]
>Though I should have done it first.

I can help updating the docs, no worries. I also want to add testing for plugins. Will think of a simple way, maybe having some custom fixtures (if we use pytest) . Any preference on pytest vs unittest ?

**Comment by nixjdm** [comment]
> I can help

:relieved: 

pytest please :)

**Pull request merged**
